---
apiVersion: batch/v1
kind: Job
metadata:
  name: hydra-migrate
  namespace: external
  labels:
    app: hydra
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: hydra-migrate
          image: mirror.gcr.io/oryd/hydra:v2.2.0
          command: ["hydra"]
          args: ["migrate", "sql", "-e", "--yes"]
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: hydra-secret
                  key: dsn
---
apiVersion: v1
kind: Secret
metadata:
  name: hydra-secret
  namespace: external
type: Opaque
stringData:
  dsn: "postgres://ory:ory-dev-password@postgresql.external.svc.cluster.local:5432/hydra_db?sslmode=disable"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
  namespace: external
  labels:
    app: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydra
  template:
    metadata:
      labels:
        app: hydra
    spec:
      containers:
        - name: hydra
          image: mirror.gcr.io/oryd/hydra:v2.2.0
          command: ["hydra"]
          args: ["serve", "-c", "/etc/config/hydra/hydra.yml", "all", "--dev"]
          ports:
            - name: public
              containerPort: 4444
            - name: admin
              containerPort: 4445
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: hydra-secret
                  key: dsn
            - name: LOG_LEAK_SENSITIVE_VALUES
              value: "true"
          volumeMounts:
            - name: hydra-config
              mountPath: /etc/config/hydra/hydra.yml
              subPath: hydra.yml
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: public
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/alive
              port: public
            initialDelaySeconds: 10
            periodSeconds: 15
      volumes:
        - name: hydra-config
          configMap:
            name: hydra-config
---
apiVersion: v1
kind: Service
metadata:
  name: hydra-public
  namespace: external
  labels:
    app: hydra
spec:
  type: ClusterIP
  ports:
    - name: public
      port: 4444
      targetPort: 4444
  selector:
    app: hydra
---
apiVersion: v1
kind: Service
metadata:
  name: hydra-admin
  namespace: external
  labels:
    app: hydra
spec:
  type: ClusterIP
  ports:
    - name: admin
      port: 4445
      targetPort: 4445
  selector:
    app: hydra
