---
apiVersion: batch/v1
kind: Job
metadata:
  name: kratos-migrate
  namespace: external
  labels:
    app: kratos
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kratos-migrate
          image: mirror.gcr.io/oryd/kratos:v1.0.0
          command: ["kratos"]
          args: ["migrate", "sql", "-e", "--yes"]
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: kratos-secret
                  key: dsn
---
apiVersion: v1
kind: Secret
metadata:
  name: kratos-secret
  namespace: external
type: Opaque
stringData:
  dsn: "postgres://ory:ory-dev-password@postgresql.external.svc.cluster.local:5432/kratos_db?sslmode=disable"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-schemas
  namespace: external
data:
  identity.schema.json: |
    {
      "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Person",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "format": "email",
              "title": "E-Mail",
              "minLength": 3,
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  }
                },
                "verification": {
                  "via": "email"
                },
                "recovery": {
                  "via": "email"
                }
              }
            },
            "username": {
              "type": "string",
              "title": "Username",
              "minLength": 3,
              "maxLength": 32
            }
          },
          "required": ["email"],
          "additionalProperties": false
        }
      }
    }
  github-mapper.json: |
    {
      "id": "github",
      "provider": "github",
      "schema_id": "default",
      "mapper_url": "base64://bG9jYWwgY2xhaW1zID0gc3RkLmV4dFZhcigiY2xhaW1zIik7Cgp7CiAgaWRlbnRpdHk6IHsKICAgIHRyYWl0czogewogICAgICBlbWFpbDogY2xhaW1zLmVtYWlsLAogICAgICBbImlmIiAiY2xhaW1zLm5hbWUiXTogdXNlcm5hbWU6IGNsYWltcy5sb2dpbiwKICAgIH0sCiAgfSwKfQo="
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
  namespace: external
  labels:
    app: kratos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kratos
  template:
    metadata:
      labels:
        app: kratos
    spec:
      containers:
        - name: kratos
          image: mirror.gcr.io/oryd/kratos:v1.0.0
          command: ["kratos"]
          args: ["serve", "-c", "/etc/config/kratos/kratos.yml", "--dev", "--watch-courier"]
          ports:
            - name: public
              containerPort: 4433
            - name: admin
              containerPort: 4434
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: kratos-secret
                  key: dsn
            - name: LOG_LEAK_SENSITIVE_VALUES
              value: "true"
          volumeMounts:
            - name: kratos-config
              mountPath: /etc/config/kratos/kratos.yml
              subPath: kratos.yml
            - name: kratos-schemas
              mountPath: /etc/config/kratos/identity.schema.json
              subPath: identity.schema.json
            - name: kratos-schemas
              mountPath: /etc/config/kratos/github-mapper.json
              subPath: github-mapper.json
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: public
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/alive
              port: public
            initialDelaySeconds: 10
            periodSeconds: 15
      volumes:
        - name: kratos-config
          configMap:
            name: kratos-config
        - name: kratos-schemas
          configMap:
            name: kratos-schemas
---
apiVersion: v1
kind: Service
metadata:
  name: kratos-public
  namespace: external
  labels:
    app: kratos
spec:
  type: ClusterIP
  ports:
    - name: public
      port: 4433
      targetPort: 4433
  selector:
    app: kratos
---
apiVersion: v1
kind: Service
metadata:
  name: kratos-admin
  namespace: external
  labels:
    app: kratos
spec:
  type: ClusterIP
  ports:
    - name: admin
      port: 4434
      targetPort: 4434
  selector:
    app: kratos
---
# Mailslurper for development emails
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailslurper
  namespace: external
  labels:
    app: mailslurper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailslurper
  template:
    metadata:
      labels:
        app: mailslurper
    spec:
      containers:
        - name: mailslurper
          image: mirror.gcr.io/lakuapik/mailslurper-alpine
          command:
            - sh
            - -c
            - cp /tmp/config.json /mailslurper/config.json && ./mailslurper
          volumeMounts:
            - name: mailslurper-config
              mountPath: /tmp/config.json
              subPath: config.json
          ports:
            - name: smtp
              containerPort: 1025
            - name: web
              containerPort: 4436
            - name: api
              containerPort: 4437
      volumes:
        - name: mailslurper-config
          configMap:
            name: mailslurper-config
---
apiVersion: v1
kind: Service
metadata:
  name: mailslurper
  namespace: external
  labels:
    app: mailslurper
spec:
  type: ClusterIP
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: web
      port: 4436
      targetPort: 4436
    - name: api
      port: 4437
      targetPort: 4437
  selector:
    app: mailslurper
