apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-smtp
  namespace: external
  labels:
    app: fake-smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-smtp
  template:
    metadata:
      labels:
        app: fake-smtp
    spec:
      containers:
        - name: fake-smtp
          image: mirror.gcr.io/haravich/fake-smtp-server
          ports:
            - containerPort: 1025
---
apiVersion: v1
kind: Service
metadata:
  name: fake-smtp-nodeport
  namespace: external
  labels:
    app: fake-smtp
spec:
  type: NodePort
  ports:
    - port: 1025
      name: smtp
      targetPort: 1025
      nodePort: 31025
    - port: 1080
      name: web
      targetPort: 1080
      nodePort: 31080
  selector:
    app: fake-smtp
