apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: contact+acme@yewolf.fr
    privateKeySecretRef:
      name: letsencrypt-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector: {}
      dns01:
        webhook:
          groupName: acme.infomaniak.com
          solverName: infomaniak
          config:
            apiTokenSecretRef:
              name: infomaniak-api-credentials
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: main-certificate
  namespace: gateway
spec:
  secretName: main-tls-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - "{{ .Domain }}"
  - "*.{{ .Domain }}"
  