---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-ui-config
  namespace: app
data:
  KRATOS_PUBLIC_URL: "http://kratos.tristan.dev.uctf.io"
  KRATOS_ADMIN_URL: "http://kratos-admin.external.svc.cluster.local:4434"
  COOKIE_SECRET: "dev-cookie-secret-for-ui-min32c"
  CSRF_COOKIE_NAME: "ory_csrf_ui"
  CSRF_COOKIE_SECRET: "dev-csrf-secret-for-ui-min-32ch"
  PORT: "3000"
  # Security settings for dev
  SECURITY_MODE: ""
  # Base path for the UI
  BASE_PATH: "/auth"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos-ui
  namespace: app
  labels:
    app: kratos-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kratos-ui
  template:
    metadata:
      labels:
        app: kratos-ui
    spec:
      containers:
        - name: kratos-ui
          image: mirror.gcr.io/oryd/kratos-selfservice-ui-node:v1.0.0
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: kratos-ui-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /auth/health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /auth/health/alive
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: kratos-ui
  namespace: app
  labels:
    app: kratos-ui
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: kratos-ui
