apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: s3-config
  namespace: seaweedfs
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
stringData:
  # this key must be an inline json config file
  seaweedfs_s3_config: '{"identities":[{"name":"anvAdmin","credentials":[{"accessKey":"dev-access","secretKey":"dev-secret"}],"actions":["Admin","Read","Write"]},{"name":"anvReadOnly","credentials":[{"accessKey":"dev-access1","secretKey":"dev-secret2"}],"actions":["Read"]}]}'
