apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: external
data:
  POSTGRES_DB: "{{ .Postgres.Admin.Database }}"
  POSTGRES_USER: "{{ .Postgres.Admin.User }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: external
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Postgres.Admin.Password }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: external
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
  namespace: external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
        - name: pgweb
          image: sosedoff/pgweb:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--bind=0.0.0.0"
            - "--listen=8081"
            - "--url=postgres://{{ .Postgres.Admin.User }}:{{ .Postgres.Admin.Password }}@postgresql-nodeport.external.svc.cluster.local:5432/{{ .Postgres.Admin.Database }}?sslmode=disable"
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: external
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: mirror.gcr.io/postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgresql-config
            - secretRef:
                name: postgresql-secret
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-nodeport
  namespace: external
  labels:
    app: postgresql
spec:
  type: NodePort
  ports:
    - port: 5432
      name: postgres
      targetPort: 5432
      nodePort: 30432
  selector:
    app: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: pgweb
  namespace: external
  labels:
    app: pgweb
spec:
  ports:
    - port: 8081
      name: http
      targetPort: 8081
  selector:
    app: pgweb
